name: Build and Deploy
defaults:
  run:
    working-directory: OpenBimRL-CreatorTool/webapp

permissions:
  contents: write
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          repository: FlorianB-DE/OpenBimRL-CreatorTool
          path: .
          set-safe-directory: true


      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm i
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: OpenBimRL-CreatorTool/webapp/dist # The folder the action should deploy.
          repository-name: FlorianB-DE/OpenBIMRL-IDE
          token: ${{ secrets.GITHUB_TOKEN }}

